package model

import "strings"

// Banner marks a markdown file as a build output rather than a source.
// It is an HTML comment, so it is invisible in rendered markdown and
// unmissable the moment someone opens the file to edit it.
//
// It lives here, in the leaf model package, because it is a fact about
// the file format that the renderer and the parser both need:
// internal/projection emits it, internal/convert strips it back off.
// Putting it in either of those makes the other depend on it, and the
// parser depending on the renderer is backwards (it also closes an
// import cycle through projection's own tests).
//
// Emitted only on the markdown surfaces whose parsers tolerate it:
// WORK.md (convert skips the preamble outright), notes files (convert
// strips it, since preambles are stored verbatim), and archive months.
// Deliberately NOT on FEEDBACK.md, which is parsed by the legacy
// internal/feedback package, nor on devboard YAML, which is not markdown.
const Banner = "<!-- generated by worklog. edits are overwritten; use a worklog command -->"

// StripBanner removes one leading Banner line, so reading a rendered file
// back and re-rendering it does not accumulate a banner per round trip.
func StripBanner(s string) string {
	if rest, ok := strings.CutPrefix(s, Banner+"\n"); ok {
		return rest
	}
	return strings.TrimPrefix(s, Banner)
}
