// Package render holds WriteAtomic, the tempfile+rename primitive
// internal/reindex uses to write INDEX.md. adb-cutover retired every
// other writer this package used to hold (block/section/archive
// splicing) — the store (internal/store) plus projection rendering
// (internal/projection) replaced them; INDEX.md is the one surface that
// stays outside the store, regenerated by internal/reindex over the
// rendered tree.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteAtomic writes lines to path with a trailing newline, via tempfile +
// rename so a partial write cannot leave the target corrupted.
func WriteAtomic(path string, lines []string) error {
	dir := filepath.Dir(path)
	base := filepath.Base(path)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("render: mkdir %s: %w", dir, err)
	}

	f, err := os.CreateTemp(dir, "."+base+".*.tmp")
	if err != nil {
		return fmt.Errorf("render: create temp in %s: %w", dir, err)
	}
	tmpName := f.Name()
	cleanup := func() { _ = os.Remove(tmpName) }

	content := strings.Join(lines, "\n")
	if len(lines) > 0 || content != "" {
		content += "\n"
	}
	if _, err := f.WriteString(content); err != nil {
		_ = f.Close()
		cleanup()
		return fmt.Errorf("render: write temp: %w", err)
	}
	if err := f.Close(); err != nil {
		cleanup()
		return fmt.Errorf("render: close temp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		cleanup()
		return fmt.Errorf("render: rename to %s: %w", path, err)
	}
	return nil
}
