package adopt

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/prestontallen/ai-devboard/worklog/internal/store/memstore"
)

// preCutover renders the fixture corpus and then de-canonicalises it the
// way a real pre-cutover corpus differs: no banner, the old document title.
// Returns roots plus a snapshot destination OUTSIDE both.
func preCutover(t *testing.T) (Roots, string) {
	t.Helper()
	_, r, _ := canonical(t)
	work := filepath.Join(r.Worklog, "WORK.md")
	data, err := os.ReadFile(work)
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)
	body = strings.ReplaceAll(body, "<!-- generated by worklog. edits are overwritten; use a worklog command -->\n", "")
	body = strings.ReplaceAll(body, "# Worklog — active", "# Work")
	if err := os.WriteFile(work, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return r, filepath.Join(t.TempDir(), "snap")
}

func opts(r Roots, dest string, apply bool) Options {
	return Options{Roots: r, SnapshotDir: dest, Apply: apply}
}

// TestApplyDryRunTouchesNothing: the default is a preview.
func TestApplyDryRunTouchesNothing(t *testing.T) {
	r, dest := preCutover(t)
	before, beforeBoard := fingerprint(t, r.Worklog), fingerprint(t, r.Devboard)

	res, err := Run(memstore.New(), opts(r, dest, false))
	if err != nil {
		t.Fatal(err)
	}
	if res.Applied {
		t.Error("dry run reported Applied")
	}
	if !res.Plan.Writes() {
		t.Error("a de-canonicalised corpus should plan writes")
	}
	equalTrees(t, before, fingerprint(t, r.Worklog), "worklog after a dry run")
	equalTrees(t, beforeBoard, fingerprint(t, r.Devboard), "devboard after a dry run")
	if _, err := os.Stat(dest); !os.IsNotExist(err) {
		t.Error("a dry run wrote a snapshot")
	}
}

// TestApplyCanonicalises is the happy path: after adoption the corpus is a
// render fixpoint, which is exactly what the write path's gate tests.
func TestApplyCanonicalises(t *testing.T) {
	r, dest := preCutover(t)
	res, err := Run(memstore.New(), opts(r, dest, true))
	if err != nil {
		t.Fatalf("adopt: %v", err)
	}
	if !res.Applied {
		t.Fatal("Applied = false")
	}
	data, err := os.ReadFile(filepath.Join(r.Worklog, "WORK.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "<!-- generated by worklog") {
		t.Errorf("WORK.md was not canonicalised:\n%s", firstLine(string(data)))
	}

	// Idempotence: a second run plans no writes at all.
	res2, err := Run(memstore.New(), opts(r, filepath.Join(t.TempDir(), "snap2"), false))
	if err != nil {
		t.Fatalf("second adopt: %v", err)
	}
	if res2.Plan.Writes() {
		for _, c := range res2.Plan.Changes {
			if c.Op != OpKeep && c.Op != OpProduce && c.Op != OpDerived {
				t.Errorf("second run still plans %s", c)
			}
		}
	}
}

// TestRefusalsLeaveLiveDirsUnchanged is criterion 10, across every gate.
func TestRefusalsLeaveLiveDirsUnchanged(t *testing.T) {
	cases := map[string]func(t *testing.T, r Roots){
		"census": func(t *testing.T, r Roots) {
			write(t, r.Worklog, "notes/stale.md.bak", "unreadable by the converter\n")
		},
		"hazard": func(t *testing.T, r Roots) {
			p := filepath.Join(r.Worklog, "WORK.md")
			data, _ := os.ReadFile(p)
			// Prose before the first section: discarded on read.
			body := strings.Replace(string(data), "## Now", "Prose the reader throws away.\n\n## Now", 1)
			if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
				t.Fatal(err)
			}
		},
		"convert": func(t *testing.T, r Roots) {
			write(t, r.Worklog, "notes/nobody-wears-this-slug.md", "# Notes\n")
		},
	}
	for name, breakIt := range cases {
		t.Run(name, func(t *testing.T) {
			r, dest := preCutover(t)
			breakIt(t, r)
			before, beforeBoard := fingerprint(t, r.Worklog), fingerprint(t, r.Devboard)

			_, err := Run(memstore.New(), opts(r, dest, true))
			if err == nil {
				t.Fatal("expected a refusal")
			}
			if !errors.Is(err, ErrRefused) {
				t.Errorf("error does not wrap ErrRefused: %v", err)
			}
			equalTrees(t, before, fingerprint(t, r.Worklog), "worklog after a "+name+" refusal")
			equalTrees(t, beforeBoard, fingerprint(t, r.Devboard), "devboard after a "+name+" refusal")
		})
	}
}

// TestRefusesSnapshotInsideLiveRoot: convert.ReadCorpusDir ingests any *.md
// under notes/ or archive/ and refuses on a note naming no ticket, so a
// backup written inside the corpus poisons every later conversion.
func TestRefusesSnapshotInsideLiveRoot(t *testing.T) {
	r, _ := preCutover(t)
	_, err := Run(memstore.New(), opts(r, filepath.Join(r.Worklog, "backup"), true))
	if err == nil {
		t.Fatal("accepted a snapshot destination inside the live root")
	}
	if !strings.Contains(err.Error(), "poison") {
		t.Errorf("error = %v, want it to explain why", err)
	}
}

// TestRollsBackWhenAStepFails: a failure after the snapshot must leave the
// corpus byte-identical, not half-applied.
func TestRollsBackWhenAStepFails(t *testing.T) {
	r, dest := preCutover(t)
	before, beforeBoard := fingerprint(t, r.Worklog), fingerprint(t, r.Devboard)

	o := opts(r, dest, true)
	o.Reindex = func() error { return errors.New("boom") }

	_, err := Run(memstore.New(), o)
	if err == nil {
		t.Fatal("expected the failure to surface")
	}
	if !strings.Contains(err.Error(), "rolled back") {
		t.Errorf("error = %v, want it to say the corpus was rolled back", err)
	}
	equalTrees(t, before, fingerprint(t, r.Worklog), "worklog after a mid-run failure")
	equalTrees(t, beforeBoard, fingerprint(t, r.Devboard), "devboard after a mid-run failure")
}

// TestApplyRunsReindex checks the hook fires in the success path, in the
// right order: after the projections land, since reindex reads them.
func TestApplyRunsReindex(t *testing.T) {
	r, dest := preCutover(t)
	var sawCanonical bool
	o := opts(r, dest, true)
	o.Reindex = func() error {
		data, err := os.ReadFile(filepath.Join(r.Worklog, "WORK.md"))
		if err != nil {
			return err
		}
		sawCanonical = strings.HasPrefix(string(data), "<!-- generated by worklog")
		return nil
	}
	if _, err := Run(memstore.New(), o); err != nil {
		t.Fatal(err)
	}
	if !sawCanonical {
		t.Error("reindex ran before the projections landed; it reads them from disk")
	}
}

func firstLine(s string) string {
	if i := strings.Index(s, "\n"); i >= 0 {
		return s[:i]
	}
	return s
}
